"""initial schema

Revision ID: 2a99db1622c7
Revises: 
Create Date: 2026-07-19 16:21:54.011075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a99db1622c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lifecycle', sa.String(length=50), nullable=False),
    sa.Column('supported_countries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('carrier_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_pickup_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pickup_type', sa.String(length=50), nullable=False),
    sa.Column('street_line_1', sa.String(length=255), nullable=False),
    sa.Column('street_line_2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state_or_region', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_points')
    op.drop_table('carrier_accounts')
    op.drop_table('carriers')
    # ### end Alembic commands ###
